create table address
(
    id               bigint generated by default as identity,
    number_apartment varchar(10),
    number_house     varchar(10),
    street           varchar(255),
    country_id       bigint,
    city_id          bigint not null,
    primary key (id)
);

create table brand_product
(
    id         bigint generated by default as identity,
    brand_name varchar(50) not null,
    primary key (id)
);


create table category_product
(
    id            bigint generated by default as identity,
    category_name varchar(50) not null,
    primary key (id)
);

create table city
(
    id         bigint generated by default as identity,
    city_name  varchar(50) not null,
    country_id bigint,
    primary key (id)
);


create table customer
(
    id           bigint generated by default as identity,
    email        varchar(50),
    first_name   varchar(50) not null,
    last_name    varchar(50) not null,
    phone_number varchar(15) not null,
    address_id   bigint      not null,
    primary key (id)
);

create table country
(
    id           bigint generated by default as identity,
    country_name varchar(50) not null,
    primary key (id)
);


create table data_order
(
    id           bigint generated by default as identity,
    order_number bigint generated by default as identity,
    customer_id  bigint,
    user_id      bigint,
    primary key (id)
);


create table model_product
(
    id         bigint generated by default as identity,
    model_name varchar(50) not null,
    primary key (id)
);


create table order_item
(
    id           bigint generated by default as identity,
    count        integer,
    price_order  double,
    order_id     bigint,
    product_id   bigint,
    status_order boolean,
    user_id      bigint,
    primary key (id)
);
create table product
(
    id                  bigint generated by default as identity,
    article             bigint generated by default as identity,
    description_product varchar(2048),
    discount            integer,
    price               double not null,
    brand_product_id    bigint,
    category_product_id bigint,
    model_product_id    bigint,
    type_product_id     bigint,
    filename            varchar(2048),
    primary key (id)
);


create table stock_balance
(
    id         bigint generated by default as identity,
    remain     integer not null,
    product_id bigint  not null,
    primary key (id)
);


create table type_product
(
    id        bigint generated by default as identity,
    type_name varchar(50) not null,
    primary key (id)
);

create table user
(
    id              bigint generated by default as identity,
    activation_code varchar(255),
    active          boolean     not null,
    email           varchar(50),
    first_name      varchar(50) not null,
    last_name       varchar(50) not null,
    password        varchar(255) not null,
    phone_number    varchar(50) not null,
    username        varchar(255),
    address_id      bigint,
    primary key (id)
);


create table user_role
(
    user_id    bigint not null,
    role_users varchar(15)
);


alter table if exists city
    add constraint fk_city_country foreign key (country_id) references country;

alter table if exists customer
    add constraint fk_customer_address foreign key (address_id) references address;

alter table if exists address
    add constraint fk_address_country foreign key (country_id) references country;

alter table if exists address
    add constraint fk_address_city foreign key (city_id) references city;

alter table if exists data_order
    add constraint fk_data_order_customer foreign key (customer_id) references customer;

alter table if exists data_order
    add constraint fk_data_order_user foreign key (user_id) references user;

alter table if exists order_item
    add constraint fk_order_item_data_order foreign key (order_id) references data_order;

alter table if exists order_item
    add constraint fk_order_item_product foreign key (product_id) references product;

alter table if exists order_item
    add constraint fk_order_item_user foreign key (user_id) references user;

alter table if exists product
    add constraint fk_product_brand foreign key (brand_product_id) references brand_product;

alter table if exists product
    add constraint fk_product_category foreign key (category_product_id) references category_product;

alter table if exists product
    add constraint fk_product_model foreign key (model_product_id) references model_product;

alter table if exists product
    add constraint fk_product_type foreign key (type_product_id) references type_product;

alter table if exists stock_balance
    add constraint fk_stock_balance_product foreign key (product_id) references product;

alter table if exists user
    add constraint fk_user_address foreign key (address_id) references address;

alter table if exists user_role
    add constraint fk_user_role_user foreign key (user_id) references user